AWSTemplateFormatVersion: 2010-09-09
Description: Creates security group for xxx server

Parameters:
    SecurityGroupName:
    Type: String 
    Description: Name of the security group to be deployed

  VpcId:
    Type: String
    Description: Select a VPC 
  
  ExampleCIDR:
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'  

Resources:
   ApplicationSecurityGroup:
     Type: AWS::EC2::SecurityGroup 
     Properties:
        GroupName: !Sub ${SecurityGroup}-sg
        GroupDescription: Security group which allows access to xxx
        VpcId: !Ref VpcId
        SecurityGroupIngress:
         - CidrIp: !Ref ExampleCIDR
           IpProtocol: tcp
           FromPort: 8080
           ToPort: 8080

        Tags:
        - Key: Name
          Value: !Sub ${SecurityGroup}-sg


